//
// Candidacy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Candidacy: JSONEncodable {
    public var id: Int64?
    public var politicalOffice: PoliticalOffice?
    public var city: City?
    public var state: State?
    public var institution: Institution?
    public var elected: Bool?
    public var resourceUri: String?
    public var electionRound: ElectionRound?
    public var candidacyStatus: CandidacyStatus?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["political_office"] = self.politicalOffice?.encodeToJSON()
        nillableDictionary["city"] = self.city?.encodeToJSON()
        nillableDictionary["state"] = self.state?.encodeToJSON()
        nillableDictionary["institution"] = self.institution?.encodeToJSON()
        nillableDictionary["elected"] = self.elected
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["election_round"] = self.electionRound?.encodeToJSON()
        nillableDictionary["candidacy_status"] = self.candidacyStatus?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
