//
// City.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class City: JSONEncodable {
    public var id: Int64?
    public var logo: String?
    public var name: String?
    public var resourceUri: String?
    public var state: State?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["logo"] = self.logo
        nillableDictionary["name"] = self.name
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["state"] = self.state?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
