//
// ElectionRound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ElectionRound: JSONEncodable {
    public var date: Date?
    public var election: String?
    public var id: Int64?
    public var resourceUri: String?
    public var roundNumber: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["election"] = self.election
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["round_number"] = self.roundNumber?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
