//
// Events.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Events: JSONEncodable {
    public var id: Int64?
    public var description: String?
    public var resourceUri: String?
    public var date: Date?
    public var politicianEventType: PoliticianEventType?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["politician_event_type"] = self.politicianEventType?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
