//
// Institution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Institution: JSONEncodable {
    public var id: Int64?
    public var logo: String?
    public var name: String?
    public var politicalOffices: [PoliticalOffices]?
    public var resourceUri: String?
    public var website: String?
    public var siglum: String?
    public var wikipedia: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["logo"] = self.logo
        nillableDictionary["name"] = self.name
        nillableDictionary["political_offices"] = self.politicalOffices?.encodeToJSON()
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["website"] = self.website
        nillableDictionary["siglum"] = self.siglum
        nillableDictionary["wikipedia"] = self.wikipedia
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
