//
// Mandates.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Mandates: JSONEncodable {
    public var id: Int64?
    public var events: [Events]?
    public var candidacies: Candidacy?
    public var dateEnd: Date?
    public var dateStart: Date?
    public var resourceUri: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["events"] = self.events?.encodeToJSON()
        nillableDictionary["candidacies"] = self.candidacies?.encodeToJSON()
        nillableDictionary["date_end"] = self.dateEnd?.encodeToJSON()
        nillableDictionary["date_start"] = self.dateStart?.encodeToJSON()
        nillableDictionary["resource_uri"] = self.resourceUri
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
