//
// Politician.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Politician: JSONEncodable {
    public var about: String?
    public var candidacies: [Candidacy]?
    public var alternativeNames: [AlternativeNames]?
    public var cpf: String?
    public var dateOfBirth: Date?
    public var education: Education?
    public var email: String?
    public var ethnicity: Ethnicities?
    public var events: [Events]?
    public var gender: String?
    public var id: Int64?
    public var maritalStatus: MaritalStatus?
    public var name: String?
    public var nationality: Nationality?
    public var occupation: Occupation?
    public var picture: String?
    public var placeOfBirth: String?
    public var politicalParties: [PoliticalParties]?
    public var resourceUri: String?
    public var state: State?
    public var website: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["about"] = self.about
        nillableDictionary["candidacies"] = self.candidacies?.encodeToJSON()
        nillableDictionary["alternative_names"] = self.alternativeNames?.encodeToJSON()
        nillableDictionary["cpf"] = self.cpf
        nillableDictionary["date_of_birth"] = self.dateOfBirth?.encodeToJSON()
        nillableDictionary["education"] = self.education?.encodeToJSON()
        nillableDictionary["email"] = self.email
        nillableDictionary["ethnicity"] = self.ethnicity?.encodeToJSON()
        nillableDictionary["events"] = self.events?.encodeToJSON()
        nillableDictionary["gender"] = self.gender
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["marital_status"] = self.maritalStatus?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["nationality"] = self.nationality?.encodeToJSON()
        nillableDictionary["occupation"] = self.occupation?.encodeToJSON()
        nillableDictionary["picture"] = self.picture
        nillableDictionary["place_of_birth"] = self.placeOfBirth
        nillableDictionary["political_parties"] = self.politicalParties?.encodeToJSON()
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["state"] = self.state?.encodeToJSON()
        nillableDictionary["website"] = self.website
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
