//
// PoliticalOffice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PoliticalOffice: JSONEncodable {
    public var description: String?
    public var id: Int64?
    public var name: String?
    public var resourceUri: String?
    public var slug: String?
    public var term: Int32?
    public var wikipedia: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["description"] = self.description
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["resource_uri"] = self.resourceUri
        nillableDictionary["slug"] = self.slug
        nillableDictionary["term"] = self.term?.encodeToJSON()
        nillableDictionary["wikipedia"] = self.wikipedia
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
