//
// State.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class State: JSONEncodable {
    public var country: Country?
    public var name: String?
    public var id: Int64?
    public var logo: String?
    public var siglum: String?
    public var slug: String?
    public var wikipedia: String?
    public var resourceUri: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["country"] = self.country?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["logo"] = self.logo
        nillableDictionary["siglum"] = self.siglum
        nillableDictionary["slug"] = self.slug
        nillableDictionary["wikipedia"] = self.wikipedia
        nillableDictionary["resource_uri"] = self.resourceUri
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
